draw_bold_text_with_bright_colors = true
background_opacity = 1

[env]
TERM = "xterm-256color"

[window]
title = "Alacritty"

  [window.padding]
  x = 6
  y = 6

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 5_000

[font]
size = 11

  [font.normal]
  family = "SauceCodePro Nerd Font"
  style = "Regular"

  [font.bold]
  family = "SauceCodePro Nerd Font"
  style = "Bold"

  [font.italic]
  family = "SauceCodePro Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "SauceCodePro Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 1

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[colors.selection]
text = "0xbbc2cf"
background = "0x282c34"

[colors.normal]
black = "0x1c1f24"
red = "0xff6c6b"
green = "0x98be65"
yellow = "0xda8548"
blue = "0x51afef"
magenta = "0xc678dd"
cyan = "0x5699af"
white = "0x202328"

[colors.bright]
black = "0x5b6268"
red = "0xda8548"
green = "0x4db5bd"
yellow = "0xecbe7b"
blue = "0x3071db"
magenta = "0xa9a1e1"
cyan = "0x46d9ff"
white = "0xdfdfdf"

[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[key_bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[key_bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Add"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Subtract"
mods = "Control"
action = "DecreaseFontSize"

[[key_bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[key_bindings]]
key = "Paste"
action = "Paste"

[[key_bindings]]
key = "Copy"
action = "Copy"

[[key_bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[key_bindings]]
key = "L"
mods = "Control"
chars = "\f"

[[key_bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"
mode = "~Alt"

[[key_bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"
mode = "~Alt"

[[key_bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[key_bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"

