[global]
	server role = standalone server
	usershare allow guests = yes

[vid]
	comment = sharing vids and movies
	path = /mnt
	read only = no
	guest ok = yes
	force user = putin
	force group = users
