---
services:
  serviceName:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOSTNAME=${HOSTNAME}
    image: MAINTAINER/IMAGE:latest
    container_name: "serviceName-${HOSTNAME}" #
    hostname: "serviceName-${HOSTNAME}" #
    env_file:
      - "${BAK_CFG_DIR}/serviceName/.env"
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/serviceName:/config" #
    ports:
      - 80:80 #
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.serviceName.loadbalancer.server.port: portNumber #
      traefik.http.routers.serviceName.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.routers.serviceName.rule: Host(`serviceName.${CF_DOMAIN}`)
      com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install

networks:
  proxy:
    external: true
