---
services:
  serviceName:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOSTNAME=${HOSTNAME}
    image: MAINTAINER/IMAGE:latest
    container_name: "serviceName-${HOSTNAME}" #
    hostname: "serviceName-${HOSTNAME}" #
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/serviceName:/config" #
    ports:
      - 80:80 #
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: portNumber #
      traefik.http.routers.serviceName.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy


networks:
  proxy:
    external: true
